<?xml version = '1.0' encoding = 'UTF-8'?>
<!--User Editing Not Allowed for Sections: oracle-xsl-mapper:schema, top level xsl:params, version attribute of the stylesheet element. GENERATED BY OIC MAPPER, DO NOT DELETE THIS LINE-->
<!--User Editing Not Allowed for Sections: oracle-xsl-mapper:schema, top level xsl:params, version attribute of the stylesheet element. GENERATED BY OIC MAPPER, DO NOT DELETE THIS LINE--><xsl:stylesheet version="2.0" xml:id="id_1" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:nstrgmpr="http://xmlns.oracle.com/cloud/adapter/REST/getESSJobStatus_REQUEST/types" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:nssrcmpr="http://xmlns.oracle.com/cloud/adapter/REST/InvokeInventoryMovement_REQUEST/types" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" ora oracle-xsl-mapper dvm oraext xsi xsd fn xp20 nssrcmpr xsl ignore01 nsmpr0 nsmpr1 nsmpr2 nsmpr3 nsmpr4" xmlns:ignore01="http://www.oracle.com/XSL/Transform/java" ignore01:ignorexmlids="true" xmlns:xml="http://www.w3.org/XML/1998/namespace" xmlns:nsmpr0="http://xmlns.oracle.com/cloud/adapter/erp/RunESSJobs_REQUEST/types" xmlns:nsmpr1="http://xmlns.oracle.com/cloud/adapter/erp/GetProductDetails_REQUEST/types" xmlns:nsmpr2="http://xmlns.oracle.com/cloud/adapters/fscmRestApp/PickSlipDetails" xmlns:nsmpr3="http://xmlns.oracle.com/cloud/adapters/fscmRestApp" xmlns:nsmpr4="http://www.oracle.com/2014/03/ic/integration/metadata" xmlns:ns43="http://xml.oracle.com/types/REST/getESSJobStatus_REQUEST">
   <oracle-xsl-mapper:schema xml:id="id_2">
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources xml:id="id_3">
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_4">
            <oracle-xsl-mapper:schema location="../../application_13/outbound_14/resourcegroup_15/InvokeInventoryMovement_REQUEST.wsdl" xml:id="id_5"/>
            <oracle-xsl-mapper:rootElement name="execute" namespace="http://xmlns.oracle.com/cloud/adapter/REST/InvokeInventoryMovement_REQUEST/types" xml:id="id_6"/>
         </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="WSDL" xml:id="id_13">
            <oracle-xsl-mapper:schema location="../../application_988/inbound_989/resourcegroup_990/RunESSJobs_REQUEST.wsdl" xml:id="id_14"/>
            <oracle-xsl-mapper:rootElement name="submitESSJobRequestResponse" namespace="http://xmlns.oracle.com/cloud/adapter/erp/RunESSJobs_REQUEST/types" xml:id="id_15"/>
            <oracle-xsl-mapper:param name="RunESSJobs" xml:id="id_16"/>
         </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="WSDL" xml:id="id_57">
            <oracle-xsl-mapper:schema location="../../application_988/inbound_989/resourcegroup_990/RunESSJobs_REQUEST.wsdl" xml:id="id_58"/>
            <oracle-xsl-mapper:rootElement name="submitESSJobRequest" namespace="http://xmlns.oracle.com/cloud/adapter/erp/RunESSJobs_REQUEST/types" xml:id="id_59"/>
            <oracle-xsl-mapper:param name="RunESSJobs_REQUEST" xml:id="id_60"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_65">
            <oracle-xsl-mapper:schema location="../../processor_2084/resourcegroup_2087/generated.wsdl" xml:id="id_66"/>
            <oracle-xsl-mapper:rootElement name="itemLots" namespace="http://xmlns.oracle.com/cloud/adapters/fscmRestApp/PickSlipDetails" xml:id="id_67"/>
            <oracle-xsl-mapper:param name="globalLotItem" xml:id="id_68"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_69">
            <oracle-xsl-mapper:schema location="../../processor_2326/resourcegroup_2329/generated.wsdl" xml:id="id_70"/>
            <oracle-xsl-mapper:rootElement name="pickLines" namespace="http://xmlns.oracle.com/cloud/adapters/fscmRestApp" xml:id="id_71"/>
            <oracle-xsl-mapper:param name="globalLotItemArray" xml:id="id_72"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="XSD" xml:id="id_73">
            <oracle-xsl-mapper:schema location="../../processor_1/resourcegroup_2/ICSIntegrationMetadata.xsd" xml:id="id_74"/>
            <oracle-xsl-mapper:rootElement name="metadata" namespace="http://www.oracle.com/2014/03/ic/integration/metadata" xml:id="id_75"/>
            <oracle-xsl-mapper:param name="self" xml:id="id_76"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets xml:id="id_7">
         <oracle-xsl-mapper:target type="WSDL" xml:id="id_8">
            <oracle-xsl-mapper:schema location="../../application_2565/inbound_2566/resourcegroup_2567/getESSJobStatus_REQUEST.wsdl" xml:id="id_9"/>
            <oracle-xsl-mapper:rootElement name="execute" namespace="http://xmlns.oracle.com/cloud/adapter/REST/getESSJobStatus_REQUEST/types" xml:id="id_10"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
   </oracle-xsl-mapper:schema>
   <xsl:param name="RunESSJobs" xml:id="id_39"/>
   <xsl:param name="ESSJobDefinitionName" xml:id="id_77"/>
   <xsl:param name="ESSJobPackageName" xml:id="id_78"/>
   <xsl:param name="RunESSJobs_REQUEST" xml:id="id_79"/>
   <xsl:param name="globalClientID" xml:id="id_80"/>
   <xsl:param name="globalLotItem" xml:id="id_82"/>
   <xsl:param name="globalLotItemArray" xml:id="id_83"/>
   <xsl:param name="globalLotQty" xml:id="id_84"/>
   <xsl:param name="globalMRNumber" xml:id="id_85"/>
   <xsl:param name="globalOrgID" xml:id="id_86"/>
   <xsl:param name="globalRemainQty" xml:id="id_87"/>
   <xsl:param name="globalTransferedQty" xml:id="id_88"/>
   <xsl:param name="self" xml:id="id_89"/>
   <xsl:param name="tracking_var_1" xml:id="id_90"/>
   <xsl:param name="tracking_var_2" xml:id="id_91"/>
   <xsl:param name="tracking_var_3" xml:id="id_92"/>
   <xsl:template match="/" xml:id="id_11">
      <nstrgmpr:execute xml:id="id_12">
         <nstrgmpr:TemplateParameters xml:id="id_54">
            <ns43:requestId xml:id="id_55">
               <xsl:value-of xml:id="id_56" select="$RunESSJobs/nsmpr0:submitESSJobRequestResponse/nsmpr0:result"/>
            </ns43:requestId>
         </nstrgmpr:TemplateParameters>
      </nstrgmpr:execute>
   </xsl:template>
</xsl:stylesheet>