<?xml version = '1.0' encoding = 'UTF-8'?>
<!--User Editing Not Allowed for Sections: oracle-xsl-mapper:schema, top level xsl:params, version attribute of the stylesheet element. GENERATED BY OIC MAPPER, DO NOT DELETE THIS LINE-->
<!--User Editing Not Allowed for Sections: oracle-xsl-mapper:schema, top level xsl:params, version attribute of the stylesheet element. GENERATED BY OIC MAPPER, DO NOT DELETE THIS LINE--><xsl:stylesheet version="2.0" xml:id="id_1" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:nstrgmpr="http://xmlns.oracle.com/cloud/adapter/erp/GetProductDetails_REQUEST/types" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:nssrcmpr="http://xmlns.oracle.com/cloud/adapter/REST/InvokeInventoryMovement_REQUEST/types" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" ora oracle-xsl-mapper dvm oraext xsi xsd fn xp20 nssrcmpr xsl ignore01 nsmpr0 nsmpr1 nsmpr2 nsmpr3 nsmpr4 nsmpr0 nssrcmpr" xmlns:ignore01="http://www.oracle.com/XSL/Transform/java" ignore01:ignorexmlids="true" xmlns:xml="http://www.w3.org/XML/1998/namespace" xmlns:nsmpr0="http://xmlns.oracle.com/cloud/adapter/REST/InvokeInventoryMovement/types" xmlns:nsmpr1="http://xmlns.oracle.com/cloud/adapter/erp/GetIMLineDetails_REQUEST/types" xmlns:nsmpr2="http://xmlns.oracle.com/cloud/adapters/fscmRestApp/PickSlipDetails" xmlns:nsmpr3="http://xmlns.oracle.com/cloud/adapters/fscmRestApp" xmlns:nsmpr4="http://www.oracle.com/2014/03/ic/integration/metadata">
   <oracle-xsl-mapper:schema xml:id="id_2">
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources xml:id="id_3">
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_4">
            <oracle-xsl-mapper:schema location="../../application_13/outbound_14/resourcegroup_15/InvokeInventoryMovement_REQUEST.wsdl" xml:id="id_5"/>
            <oracle-xsl-mapper:rootElement name="execute" namespace="http://xmlns.oracle.com/cloud/adapter/REST/InvokeInventoryMovement_REQUEST/types" xml:id="id_6"/>
         </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="WSDL" xml:id="id_13">
            <oracle-xsl-mapper:schema location="../../processor_236/resourcegroup_916/generated.wsdl" xml:id="id_14"/>
            <oracle-xsl-mapper:rootElement name="lineDetails" namespace="http://xmlns.oracle.com/cloud/adapter/REST/InvokeInventoryMovement/types" xml:id="id_15"/>
            <oracle-xsl-mapper:param name="ForLoopRequstLinesVar" xml:id="id_16"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_69">
            <oracle-xsl-mapper:schema location="../../processor_2084/resourcegroup_2087/generated.wsdl" xml:id="id_70"/>
            <oracle-xsl-mapper:rootElement name="itemLots" namespace="http://xmlns.oracle.com/cloud/adapters/fscmRestApp/PickSlipDetails" xml:id="id_71"/>
            <oracle-xsl-mapper:param name="globalLotItem" xml:id="id_72"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_73">
            <oracle-xsl-mapper:schema location="../../processor_2326/resourcegroup_2329/generated.wsdl" xml:id="id_74"/>
            <oracle-xsl-mapper:rootElement name="pickLines" namespace="http://xmlns.oracle.com/cloud/adapters/fscmRestApp" xml:id="id_75"/>
            <oracle-xsl-mapper:param name="globalLotItemArray" xml:id="id_76"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="XSD" xml:id="id_77">
            <oracle-xsl-mapper:schema location="../../processor_1/resourcegroup_2/ICSIntegrationMetadata.xsd" xml:id="id_78"/>
            <oracle-xsl-mapper:rootElement name="metadata" namespace="http://www.oracle.com/2014/03/ic/integration/metadata" xml:id="id_79"/>
            <oracle-xsl-mapper:param name="self" xml:id="id_80"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets xml:id="id_7">
         <oracle-xsl-mapper:target type="WSDL" xml:id="id_8">
            <oracle-xsl-mapper:schema location="../../application_2461/inbound_2462/resourcegroup_2463/GetProductDetails_REQUEST.wsdl" xml:id="id_9"/>
            <oracle-xsl-mapper:rootElement name="getAll" namespace="http://xmlns.oracle.com/cloud/adapter/erp/GetProductDetails_REQUEST/types" xml:id="id_10"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
   </oracle-xsl-mapper:schema>
   <xsl:param name="ForLoopRequstLinesVar" xml:id="id_45"/>
   <xsl:param name="globalClientID" xml:id="id_81"/>
   <xsl:param name="globalLotItem" xml:id="id_83"/>
   <xsl:param name="globalLotItemArray" xml:id="id_84"/>
   <xsl:param name="globalLotQty" xml:id="id_85"/>
   <xsl:param name="globalMRNumber" xml:id="id_86"/>
   <xsl:param name="globalOrgID" xml:id="id_87"/>
   <xsl:param name="globalRemainQty" xml:id="id_88"/>
   <xsl:param name="globalTransferedQty" xml:id="id_89"/>
   <xsl:param name="self" xml:id="id_90"/>
   <xsl:param name="tracking_var_1" xml:id="id_91"/>
   <xsl:param name="tracking_var_2" xml:id="id_92"/>
   <xsl:param name="tracking_var_3" xml:id="id_93"/>
   <xsl:template match="/" xml:id="id_11">
      <nstrgmpr:getAll xml:id="id_12">
         <nstrgmpr:QueryParameters xml:id="id_62">
            <nstrgmpr:query xml:id="id_63">
               <xsl:value-of xml:id="id_64" select="concat (&quot;ItemNumber=&quot;, $ForLoopRequstLinesVar/nsmpr0:lineDetails/nsmpr0:productCode, &quot;;&quot;, &quot;OrganizationCode=&quot;, /nssrcmpr:execute/nsmpr0:request-wrapper/nsmpr0:sourceStockholder )"/>
            </nstrgmpr:query>
         </nstrgmpr:QueryParameters>
      </nstrgmpr:getAll>
   </xsl:template>
</xsl:stylesheet>