<?xml version = '1.0' encoding = 'UTF-8'?>
<!--User Editing Not Allowed for Sections: oracle-xsl-mapper:schema, top level xsl:params, version attribute of the stylesheet element. GENERATED BY OIC MAPPER, DO NOT DELETE THIS LINE-->
<!--User Editing Not Allowed for Sections: oracle-xsl-mapper:schema, top level xsl:params, version attribute of the stylesheet element. GENERATED BY OIC MAPPER, DO NOT DELETE THIS LINE--><xsl:stylesheet xmlns:nssrcmpr="http://www.oracle.com/2014/03/ics/schedule" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:nstrgmpr="http://xmlns.oracle.com/types/GetInventoryMovementDetails/1729060529055/OutboundSOAPRequestDocument" xmlns:ignore01="http://www.oracle.com/XSL/Transform/java" xmlns:nsmpr0="http://www.oracle.com/2014/03/ic/integration/metadata" xmlns:tns="http://xmlns.oracle.com/oxp/service/PublicReportService" version="2.0" xml:id="id_1" exclude-result-prefixes=" nssrcmpr ora oracle-xsl-mapper dvm oraext xsi xsd fn xp20 xsl ignore01 nsmpr0 nssrcmpr nssrcmpr nssrcmpr fn fn fn dvm" ignore01:ignorexmlids="true" xmlns:xml="http://www.w3.org/XML/1998/namespace">
        <oracle-xsl-mapper:schema xml:id="id_2">
              <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
              <oracle-xsl-mapper:mapSources xml:id="id_3">
                    <oracle-xsl-mapper:source type="XSD" xml:id="id_4">
                          <oracle-xsl-mapper:schema location="../../processor_8/resourcegroup_9/ICSSchedule_1.xsd" xml:id="id_5"/>
                          <oracle-xsl-mapper:rootElement name="schedule" namespace="http://www.oracle.com/2014/03/ics/schedule" xml:id="id_6"/>
                    </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
              <oracle-xsl-mapper:mapTargets xml:id="id_7">
                    <oracle-xsl-mapper:target type="WSDL" xml:id="id_8">
                          <oracle-xsl-mapper:schema location="../../application_110/inbound_111/resourcegroup_112/GetInventoryMovementDetails_REQUEST.wsdl" xml:id="id_9"/>
                          <oracle-xsl-mapper:rootElement name="OutboundSOAPRequestDocument" namespace="http://xmlns.oracle.com/types/GetInventoryMovementDetails/1729060529055/OutboundSOAPRequestDocument" xml:id="id_10"/>
                    </oracle-xsl-mapper:target>
              </oracle-xsl-mapper:mapTargets>
        </oracle-xsl-mapper:schema>
   <xsl:template match="/" xml:id="id_11">
              <nstrgmpr:OutboundSOAPRequestDocument xml:id="id_12">
                    <nstrgmpr:Body xml:id="id_21">
                          <tns:runReport xml:id="id_22">
                                <tns:reportRequest xml:id="id_23">
                                      <tns:attributeFormat xml:id="id_26">
                                            <xsl:value-of xml:id="id_27" select="&quot;xml&quot;"/>
                                      </tns:attributeFormat>
                                      <tns:flattenXML xml:id="id_28">
                                            <xsl:value-of xml:id="id_29" select="&quot;false&quot;"/>
                                      </tns:flattenXML>
                                      <tns:parameterNameValues xml:id="id_32">
                                            <tns:item xml:id="id_33">
                                                  <tns:name xml:id="id_34">
                                                        <xsl:value-of xml:id="id_35" select="&quot;username&quot;"/>
                                                  </tns:name>
                                                  <tns:values xml:id="id_68">
                           <tns:item xml:id="id_69">
                              <xsl:value-of xml:id="id_70" select="dvm:lookupValue (&quot;AE_Common_Lookup&quot;, &quot;Key&quot;, &quot;IntegrationFusionUser&quot;, &quot;Key&quot;, &quot;&quot; )"/>
                           </tns:item>
                        </tns:values>
                     </tns:item>
                                            <tns:item xml:id="id_33">
                                                  <tns:name xml:id="id_47">
                                                        <xsl:value-of xml:id="id_48" select="&quot;creationDate&quot;"/>
                                                  </tns:name>
                                                  <tns:values xml:id="id_57">
                                                        <tns:item xml:id="id_79">
                              <xsl:value-of xml:id="id_80" select="xsd:date ((fn:current-date() - xsd:dayTimeDuration (&quot;P1D&quot; )) )"/>
                           </tns:item>
                        </tns:values>
                                            </tns:item>
                                      </tns:parameterNameValues>
                                      <tns:reportAbsolutePath xml:id="id_24">
                                            <xsl:value-of xml:id="id_25" select="&quot;/Custom/iSupervisor/Inventory Movement/Inventory Movement Details Report.xdo&quot;"/>
                                      </tns:reportAbsolutePath>
                                      <tns:sizeOfDataChunkDownload xml:id="id_30">
                                            <xsl:value-of xml:id="id_31" select="&quot;-1&quot;"/>
                                      </tns:sizeOfDataChunkDownload>
                                </tns:reportRequest>
                          </tns:runReport>
                    </nstrgmpr:Body>
              </nstrgmpr:OutboundSOAPRequestDocument>
        </xsl:template>
  </xsl:stylesheet>