<?xml version = '1.0' encoding = 'UTF-8'?>
<!--User Editing Not Allowed for Sections: oracle-xsl-mapper:schema, top level xsl:params, version attribute of the stylesheet element. GENERATED BY OIC MAPPER, DO NOT DELETE THIS LINE-->
<!--User Editing Not Allowed for Sections: oracle-xsl-mapper:schema, top level xsl:params, version attribute of the stylesheet element. GENERATED BY OIC MAPPER, DO NOT DELETE THIS LINE--><xsl:stylesheet version="2.0" xml:id="id_1" xmlns:nssrcmpr="http://www.oracle.com/2014/03/ics/schedule" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:nstrgmpr="http://xmlns.oracle.com/cloud/adapter/collocatedics/InvokeCommonErrorEmailNotification_REQUEST/types" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" nssrcmpr ora oracle-xsl-mapper dvm oraext xsi xsd fn xp20 xsl ignore01 nsmpr0 nsmpr1 fn" xmlns:ignore01="http://www.oracle.com/XSL/Transform/java" ignore01:ignorexmlids="true" xmlns:xml="http://www.w3.org/XML/1998/namespace" xmlns:nsmpr0="http://www.oracle.com/2014/03/ics/fault" xmlns:nsmpr1="http://www.oracle.com/2014/03/ic/integration/metadata" xmlns:ns20="http://www.oracle.rest.converters.autogeneratedns.com/collocatedics/InvokeCommonErrorEmailNotification_REQUEST">
   <oracle-xsl-mapper:schema xml:id="id_2">
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources xml:id="id_3">
         <oracle-xsl-mapper:source type="XSD" xml:id="id_4">
            <oracle-xsl-mapper:schema location="../../processor_8/resourcegroup_9/ICSSchedule_1.xsd" xml:id="id_5"/>
            <oracle-xsl-mapper:rootElement name="schedule" namespace="http://www.oracle.com/2014/03/ics/schedule" xml:id="id_6"/>
         </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="XSD" xml:id="id_13">
            <oracle-xsl-mapper:schema location="../../processor_311/resourcegroup_312/ICSFault.xsd" xml:id="id_14"/>
            <oracle-xsl-mapper:rootElement name="fault" namespace="http://www.oracle.com/2014/03/ics/fault" xml:id="id_15"/>
            <oracle-xsl-mapper:param name="GlobalFaultObject" xml:id="id_16"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="XSD" xml:id="id_17">
            <oracle-xsl-mapper:schema location="../../processor_13/resourcegroup_14/ICSIntegrationMetadata.xsd" xml:id="id_18"/>
            <oracle-xsl-mapper:rootElement name="metadata" namespace="http://www.oracle.com/2014/03/ic/integration/metadata" xml:id="id_19"/>
            <oracle-xsl-mapper:param name="self" xml:id="id_20"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets xml:id="id_7">
         <oracle-xsl-mapper:target type="WSDL" xml:id="id_8">
            <oracle-xsl-mapper:schema location="../../application_568/inbound_569/resourcegroup_570/InvokeCommonErrorEmailNotification_REQUEST.wsdl" xml:id="id_9"/>
            <oracle-xsl-mapper:rootElement name="POST" namespace="http://xmlns.oracle.com/cloud/adapter/collocatedics/InvokeCommonErrorEmailNotification_REQUEST/types" xml:id="id_10"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
   </oracle-xsl-mapper:schema>
   <xsl:param name="GlobalFaultObject" xml:id="id_21"/>
   <xsl:param name="self" xml:id="id_22"/>
   <xsl:template match="/" xml:id="id_11">
      <nstrgmpr:POST xml:id="id_12">
         <nstrgmpr:components.schemas.request-wrapper xml:id="id_26">
            <ns20:errorCode xml:id="id_27">
               <xsl:value-of xml:id="id_28" select="$GlobalFaultObject/nsmpr0:fault/nsmpr0:errorCode"/>
            </ns20:errorCode>
            <ns20:integrationName xml:id="id_29">
               <xsl:value-of xml:id="id_30" select="$self/nsmpr1:metadata/nsmpr1:integration/nsmpr1:name"/>
            </ns20:integrationName>
            <ns20:instanceID xml:id="id_31">
               <xsl:value-of xml:id="id_32" select="$self/nsmpr1:metadata/nsmpr1:runtime/nsmpr1:instanceId"/>
            </ns20:instanceID>
            <ns20:trackingID xml:id="id_37">
               <xsl:value-of xml:id="id_38" select="'Date'"/>
            </ns20:trackingID>
            <ns20:trackingValue xml:id="id_39">
               <xsl:value-of xml:id="id_40" select="substring (/nssrcmpr:schedule/nssrcmpr:startTime, 1, 10 )"/>
            </ns20:trackingValue>
            <ns20:errorType xml:id="id_33">
               <xsl:value-of xml:id="id_34" select="dvm:lookupValue (&quot;AE_Common_Error_Messages_Lookup&quot;, &quot;Code&quot;, &quot;iSupNL:noIMFound&quot;, &quot;ErrorType&quot;, &quot;ERROR_UNHANDLED&quot; )"/>
            </ns20:errorType>
            <ns20:errorDesc xml:id="id_35">
               <xsl:value-of xml:id="id_36" select="dvm:lookupValue (&quot;AE_Common_Error_Messages_Lookup&quot;, &quot;Code&quot;, &quot;iSupNL:noIMFound&quot;, &quot;ErrorDescription&quot;, &quot;Unhandled Error - Please check the logs for more details.&quot; )"/>
            </ns20:errorDesc>
         </nstrgmpr:components.schemas.request-wrapper>
      </nstrgmpr:POST>
   </xsl:template>
</xsl:stylesheet>