<?xml version = '1.0' encoding = 'UTF-8'?>
<!--User Editing Not Allowed for Sections: oracle-xsl-mapper:schema, top level xsl:params, version attribute of the stylesheet element. GENERATED BY OIC MAPPER, DO NOT DELETE THIS LINE-->
<!--User Editing Not Allowed for Sections: oracle-xsl-mapper:schema, top level xsl:params, version attribute of the stylesheet element. GENERATED BY OIC MAPPER, DO NOT DELETE THIS LINE--><xsl:stylesheet version="2.0" xml:id="id_1" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:nssrcmpr="http://xmlns.oracle.com/cloud/adapter/REST/InvokeInventoryMovement_REQUEST/types" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:nstrgmpr="http://xmlns.oracle.com/cloud/adapter/collocatedics/CallCommonErrorNotifyHandler_REQUEST/types" exclude-result-prefixes=" ora oracle-xsl-mapper dvm oraext xsi xsd fn xp20 nssrcmpr xsl ignore01 nsmpr0 nsmpr1 nsmpr2 ns22 nssrcmpr" xmlns:ignore01="http://www.oracle.com/XSL/Transform/java" ignore01:ignorexmlids="true" xmlns:xml="http://www.w3.org/XML/1998/namespace" xmlns:nsmpr0="http://www.oracle.com/2014/03/ics/fault" xmlns:nsmpr1="http://www.oracle.com/2014/03/ic/integration/metadata" xmlns:ns21="http://www.oracle.rest.converters.autogeneratedns.com/collocatedics/CallCommonErrorNotifyHandler_REQUEST" xmlns:ns22="http://xmlns.oracle.com/cloud/adapter/REST/InvokeInventoryMovement/types" xmlns:nsmpr2="http://xmlns.oracle.com/cloud/adapter/erp/GetIMLineDetails_REQUEST/types">
   <oracle-xsl-mapper:schema xml:id="id_2">
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources xml:id="id_3">
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_4">
            <oracle-xsl-mapper:schema location="../../application_13/outbound_14/resourcegroup_15/InvokeInventoryMovement_REQUEST.wsdl" xml:id="id_5"/>
            <oracle-xsl-mapper:rootElement name="execute" namespace="http://xmlns.oracle.com/cloud/adapter/REST/InvokeInventoryMovement_REQUEST/types" xml:id="id_6"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="XSD" xml:id="id_17">
            <oracle-xsl-mapper:schema location="../../processor_1/resourcegroup_2/ICSIntegrationMetadata.xsd" xml:id="id_18"/>
            <oracle-xsl-mapper:rootElement name="metadata" namespace="http://www.oracle.com/2014/03/ic/integration/metadata" xml:id="id_19"/>
            <oracle-xsl-mapper:param name="self" xml:id="id_20"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets xml:id="id_7">
         <oracle-xsl-mapper:target type="WSDL" xml:id="id_8">
            <oracle-xsl-mapper:schema location="../../application_189/inbound_190/resourcegroup_191/CallCommonErrorNotifyHandler_REQUEST.wsdl" xml:id="id_9"/>
            <oracle-xsl-mapper:rootElement name="POST" namespace="http://xmlns.oracle.com/cloud/adapter/collocatedics/CallCommonErrorNotifyHandler_REQUEST/types" xml:id="id_10"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
   </oracle-xsl-mapper:schema>
   <xsl:param name="errorCode" xml:id="id_22"/>
   <xsl:param name="errorDesc" xml:id="id_23"/>
   <xsl:param name="errorType" xml:id="id_24"/>
   <xsl:param name="self" xml:id="id_26"/>
   <xsl:template match="/" xml:id="id_11">
      <nstrgmpr:POST xml:id="id_12">
         <nstrgmpr:components.schemas.request-wrapper xml:id="id_30">
            <ns21:errorCode xml:id="id_31">
               <xsl:value-of xml:id="id_32" select="$errorCode"/>
            </ns21:errorCode>
            <ns21:integrationName xml:id="id_37">
               <xsl:value-of xml:id="id_38" select="$self/nsmpr1:metadata/nsmpr1:integration/nsmpr1:name"/>
            </ns21:integrationName>
            <ns21:instanceID xml:id="id_41">
               <xsl:value-of xml:id="id_42" select="$self/nsmpr1:metadata/nsmpr1:runtime/nsmpr1:instanceId"/>
            </ns21:instanceID>
            <ns21:trackingID xml:id="id_54">
               <xsl:value-of xml:id="id_55" select="&quot;Issue Number&quot;"/>
            </ns21:trackingID>
            <ns21:trackingValue xml:id="id_52">
               <xsl:value-of xml:id="id_53" select="/nssrcmpr:execute/ns22:request-wrapper/ns22:issueNumber"/>
            </ns21:trackingValue>
            <ns21:errorType xml:id="id_33">
               <xsl:value-of xml:id="id_34" select="$errorType"/>
            </ns21:errorType>
            <ns21:errorDesc xml:id="id_35">
               <xsl:value-of xml:id="id_36" select="$errorDesc"/>
            </ns21:errorDesc>
         </nstrgmpr:components.schemas.request-wrapper>
      </nstrgmpr:POST>
   </xsl:template>
</xsl:stylesheet>