<?xml version = '1.0' encoding = 'UTF-8'?>
<!--User Editing Not Allowed for Sections: oracle-xsl-mapper:schema, top level xsl:params, version attribute of the stylesheet element. GENERATED BY OIC MAPPER, DO NOT DELETE THIS LINE-->
<!--User Editing Not Allowed for Sections: oracle-xsl-mapper:schema, top level xsl:params, version attribute of the stylesheet element. GENERATED BY OIC MAPPER, DO NOT DELETE THIS LINE--><xsl:stylesheet version="2.0" xml:id="id_1" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:nstrgmpr="http://xmlns.oracle.com/cloud/adapter/erp/getMovementRequest_REQUEST/types" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:nssrcmpr="http://xmlns.oracle.com/cloud/adapter/REST/InvokeInventoryMovement_REQUEST/types" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" ora oracle-xsl-mapper dvm oraext xsi xsd fn xp20 nssrcmpr xsl ignore01 nsmpr0 nsmpr1 nsmpr2 nsmpr3 ns23 fn nssrcmpr nsmpr4 nsmpr5" xmlns:ignore01="http://www.oracle.com/XSL/Transform/java" ignore01:ignorexmlids="true" xmlns:xml="http://www.w3.org/XML/1998/namespace" xmlns:nsmpr0="http://xmlns.oracle.com/cloud/adapter/erp/GetProductDetails_REQUEST/types" xmlns:nsmpr1="http://xmlns.oracle.com/cloud/adapters/fscmRestApp/PickSlipDetails" xmlns:nsmpr2="http://xmlns.oracle.com/cloud/adapters/fscmRestApp" xmlns:nsmpr3="http://www.oracle.com/2014/03/ic/integration/metadata" xmlns:ns23="http://xmlns.oracle.com/cloud/adapter/REST/InvokeInventoryMovement/types" xmlns:nsmpr4="http://xmlns.oracle.com/cloud/adapter/erp/GetPickSlipDetails_REQUEST/types" xmlns:nsmpr5="http://xmlns.oracle.com/cloud/adapter/erp/CreateMovementRequest_REQUEST/types">
   <oracle-xsl-mapper:schema xml:id="id_2">
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources xml:id="id_3">
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_4">
            <oracle-xsl-mapper:schema location="../../application_13/outbound_14/resourcegroup_15/InvokeInventoryMovement_REQUEST.wsdl" xml:id="id_5"/>
            <oracle-xsl-mapper:rootElement name="execute" namespace="http://xmlns.oracle.com/cloud/adapter/REST/InvokeInventoryMovement_REQUEST/types" xml:id="id_6"/>
         </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="WSDL" xml:id="id_92">
            <oracle-xsl-mapper:schema location="../../processor_3971/resourcegroup_3974/generated.wsdl" xml:id="id_93"/>
            <oracle-xsl-mapper:rootElement name="lines" namespace="http://xmlns.oracle.com/cloud/adapters/fscmRestApp" xml:id="id_94"/>
            <oracle-xsl-mapper:param name="globalIMLine" xml:id="id_95"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_96">
            <oracle-xsl-mapper:schema location="../../processor_3980/resourcegroup_3983/generated.wsdl" xml:id="id_97"/>
            <oracle-xsl-mapper:rootElement name="InventoryMovementRequests" namespace="http://xmlns.oracle.com/cloud/adapter/erp/CreateMovementRequest_REQUEST/types" xml:id="id_98"/>
            <oracle-xsl-mapper:param name="globalIMLineArray" xml:id="id_99"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_100">
            <oracle-xsl-mapper:schema location="../../processor_2084/resourcegroup_2087/generated.wsdl" xml:id="id_101"/>
            <oracle-xsl-mapper:rootElement name="itemLots" namespace="http://xmlns.oracle.com/cloud/adapters/fscmRestApp/PickSlipDetails" xml:id="id_102"/>
            <oracle-xsl-mapper:param name="globalLotItem" xml:id="id_103"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_104">
            <oracle-xsl-mapper:schema location="../../processor_2326/resourcegroup_2329/generated.wsdl" xml:id="id_105"/>
            <oracle-xsl-mapper:rootElement name="pickLines" namespace="http://xmlns.oracle.com/cloud/adapters/fscmRestApp" xml:id="id_106"/>
            <oracle-xsl-mapper:param name="globalLotItemArray" xml:id="id_107"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_108">
            <oracle-xsl-mapper:schema location="../../processor_3132/resourcegroup_3135/generated.wsdl" xml:id="id_109"/>
            <oracle-xsl-mapper:rootElement name="pickLines" namespace="http://xmlns.oracle.com/cloud/adapters/fscmRestApp" xml:id="id_110"/>
            <oracle-xsl-mapper:param name="globalPickLine" xml:id="id_111"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_112">
            <oracle-xsl-mapper:schema location="../../processor_3141/resourcegroup_3144/generated.wsdl" xml:id="id_113"/>
            <oracle-xsl-mapper:rootElement name="items" namespace="http://xmlns.oracle.com/cloud/adapter/erp/GetPickSlipDetails_REQUEST/types" xml:id="id_114"/>
            <oracle-xsl-mapper:param name="globalPickLineArray" xml:id="id_115"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="XSD" xml:id="id_116">
            <oracle-xsl-mapper:schema location="../../processor_1/resourcegroup_2/ICSIntegrationMetadata.xsd" xml:id="id_117"/>
            <oracle-xsl-mapper:rootElement name="metadata" namespace="http://www.oracle.com/2014/03/ic/integration/metadata" xml:id="id_118"/>
            <oracle-xsl-mapper:param name="self" xml:id="id_119"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets xml:id="id_7">
         <oracle-xsl-mapper:target type="WSDL" xml:id="id_8">
            <oracle-xsl-mapper:schema location="../../application_2953/inbound_2954/resourcegroup_2955/getMovementRequest_REQUEST.wsdl" xml:id="id_9"/>
            <oracle-xsl-mapper:rootElement name="getAll" namespace="http://xmlns.oracle.com/cloud/adapter/erp/getMovementRequest_REQUEST/types" xml:id="id_10"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
   </oracle-xsl-mapper:schema>
   <xsl:param name="globalClientID" xml:id="id_120"/>
   <xsl:param name="globalIMLine" xml:id="id_121"/>
   <xsl:param name="globalIMLineArray" xml:id="id_122"/>
   <xsl:param name="globalJobStatus" xml:id="id_123"/>
   <xsl:param name="globalLotItem" xml:id="id_124"/>
   <xsl:param name="globalLotItemArray" xml:id="id_125"/>
   <xsl:param name="globalLotQty" xml:id="id_126"/>
   <xsl:param name="globalMRNumber" xml:id="id_127"/>
   <xsl:param name="globalOrgID" xml:id="id_128"/>
   <xsl:param name="globalPickLine" xml:id="id_129"/>
   <xsl:param name="globalPickLineArray" xml:id="id_130"/>
   <xsl:param name="globalRemainQty" xml:id="id_131"/>
   <xsl:param name="globalTransferedQty" xml:id="id_132"/>
   <xsl:param name="self" xml:id="id_133"/>
   <xsl:param name="tracking_var_1" xml:id="id_134"/>
   <xsl:param name="tracking_var_2" xml:id="id_135"/>
   <xsl:param name="tracking_var_3" xml:id="id_136"/>
   <xsl:template match="/" xml:id="id_11">
      <nstrgmpr:getAll xml:id="id_12">
         <nstrgmpr:QueryParameters xml:id="id_42">
            <nstrgmpr:expand xml:id="id_90">
               <xsl:value-of xml:id="id_91" select="&quot;all&quot;"/>
            </nstrgmpr:expand>
            <nstrgmpr:query xml:id="id_43">
               <xsl:value-of xml:id="id_44" select="concat (&quot;RequestNumber=&quot;, /nssrcmpr:execute/ns23:request-wrapper/ns23:issueNumber )"/>
            </nstrgmpr:query>
         </nstrgmpr:QueryParameters>
      </nstrgmpr:getAll>
   </xsl:template>
</xsl:stylesheet>