<?xml version = '1.0' encoding = 'UTF-8'?>
<!--User Editing Not Allowed for Sections: oracle-xsl-mapper:schema, top level xsl:params, version attribute of the stylesheet element. GENERATED BY OIC MAPPER, DO NOT DELETE THIS LINE-->
<!--User Editing Not Allowed for Sections: oracle-xsl-mapper:schema, top level xsl:params, version attribute of the stylesheet element. GENERATED BY OIC MAPPER, DO NOT DELETE THIS LINE--><xsl:stylesheet version="2.0" xml:id="id_1" xmlns:nstrgmpr="http://xmlns.oracle.com/cloud/adapter/erp/RunESSJobs_REQUEST/types" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:nssrcmpr="http://xmlns.oracle.com/cloud/adapter/REST/InvokeInventoryMovement_REQUEST/types" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" ora oracle-xsl-mapper dvm oraext xsi xsd fn xp20 nssrcmpr xsl ignore01 nsmpr0 nsmpr1 nsmpr2 nsmpr3 nsmpr4 nsmpr5 nsmpr6" xmlns:ignore01="http://www.oracle.com/XSL/Transform/java" ignore01:ignorexmlids="true" xmlns:xml="http://www.w3.org/XML/1998/namespace" xmlns:nsmpr0="http://xmlns.oracle.com/cloud/adapter/erp/GetIMLineDetails_REQUEST/types" xmlns:nsmpr1="http://www.oracle.com/2014/03/ic/integration/metadata" xmlns:ns21="http://xmlns.oracle.com/cloud/adapter/REST/InvokeInventoryMovement/types" xmlns:nsmpr2="http://xmlns.oracle.com/cloud/adapters/fscmRestApp/PickSlipDetails" xmlns:nsmpr3="http://xmlns.oracle.com/cloud/adapter/erp/GetPickSlipDetails_REQUEST/types" xmlns:nsmpr4="http://xmlns.oracle.com/cloud/adapter/erp/GetProductDetails_REQUEST/types" xmlns:nsmpr5="http://xmlns.oracle.com/cloud/adapters/fscmRestApp" xmlns:nsmpr6="http://xmlns.oracle.com/cloud/adapter/erp/GetPickSlipDetail_REQUEST/types">
   <oracle-xsl-mapper:schema xml:id="id_2">
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources xml:id="id_3">
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_4">
            <oracle-xsl-mapper:schema location="../../application_13/outbound_14/resourcegroup_15/InvokeInventoryMovement_REQUEST.wsdl" xml:id="id_5"/>
            <oracle-xsl-mapper:rootElement name="execute" namespace="http://xmlns.oracle.com/cloud/adapter/REST/InvokeInventoryMovement_REQUEST/types" xml:id="id_6"/>
         </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="WSDL" xml:id="id_256">
            <oracle-xsl-mapper:schema location="../../application_3456/inbound_3457/resourcegroup_3458/GetPickSlipDetail_REQUEST.wsdl" xml:id="id_257"/>
            <oracle-xsl-mapper:rootElement name="getAllResponse" namespace="http://xmlns.oracle.com/cloud/adapter/erp/GetPickSlipDetail_REQUEST/types" xml:id="id_258"/>
            <oracle-xsl-mapper:param name="GetPickSlipDetail" xml:id="id_259"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_260">
            <oracle-xsl-mapper:schema location="../../application_3456/inbound_3457/resourcegroup_3458/GetPickSlipDetail_REQUEST.wsdl" xml:id="id_261"/>
            <oracle-xsl-mapper:rootElement name="getAll" namespace="http://xmlns.oracle.com/cloud/adapter/erp/GetPickSlipDetail_REQUEST/types" xml:id="id_262"/>
            <oracle-xsl-mapper:param name="GetPickSlipDetail_REQUEST" xml:id="id_263"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_268">
            <oracle-xsl-mapper:schema location="../../processor_2084/resourcegroup_2087/generated.wsdl" xml:id="id_269"/>
            <oracle-xsl-mapper:rootElement name="itemLots" namespace="http://xmlns.oracle.com/cloud/adapters/fscmRestApp/PickSlipDetails" xml:id="id_270"/>
            <oracle-xsl-mapper:param name="globalLotItem" xml:id="id_271"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_272">
            <oracle-xsl-mapper:schema location="../../processor_2326/resourcegroup_2329/generated.wsdl" xml:id="id_273"/>
            <oracle-xsl-mapper:rootElement name="pickLines" namespace="http://xmlns.oracle.com/cloud/adapters/fscmRestApp" xml:id="id_274"/>
            <oracle-xsl-mapper:param name="globalLotItemArray" xml:id="id_275"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_276">
            <oracle-xsl-mapper:schema location="../../processor_3132/resourcegroup_3135/generated.wsdl" xml:id="id_277"/>
            <oracle-xsl-mapper:rootElement name="pickLines" namespace="http://xmlns.oracle.com/cloud/adapters/fscmRestApp" xml:id="id_278"/>
            <oracle-xsl-mapper:param name="globalPickLine" xml:id="id_279"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_280">
            <oracle-xsl-mapper:schema location="../../processor_3141/resourcegroup_3144/generated.wsdl" xml:id="id_281"/>
            <oracle-xsl-mapper:rootElement name="items" namespace="http://xmlns.oracle.com/cloud/adapter/erp/GetPickSlipDetails_REQUEST/types" xml:id="id_282"/>
            <oracle-xsl-mapper:param name="globalPickLineArray" xml:id="id_283"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="XSD" xml:id="id_284">
            <oracle-xsl-mapper:schema location="../../processor_1/resourcegroup_2/ICSIntegrationMetadata.xsd" xml:id="id_285"/>
            <oracle-xsl-mapper:rootElement name="metadata" namespace="http://www.oracle.com/2014/03/ic/integration/metadata" xml:id="id_286"/>
            <oracle-xsl-mapper:param name="self" xml:id="id_287"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets xml:id="id_7">
         <oracle-xsl-mapper:target type="WSDL" xml:id="id_8">
            <oracle-xsl-mapper:schema location="../../application_988/inbound_989/resourcegroup_990/RunESSJobs_REQUEST.wsdl" xml:id="id_9"/>
            <oracle-xsl-mapper:rootElement name="submitESSJobRequest" namespace="http://xmlns.oracle.com/cloud/adapter/erp/RunESSJobs_REQUEST/types" xml:id="id_10"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
   </oracle-xsl-mapper:schema>
   <xsl:param name="ESSJobDefinitionName" xml:id="id_33"/>
   <xsl:param name="ESSJobPackageName" xml:id="id_34"/>
   <xsl:param name="globalMRNumber" xml:id="id_214"/>
   <xsl:param name="globalOrgID" xml:id="id_255"/>
   <xsl:param name="GetPickSlipDetail" xml:id="id_288"/>
   <xsl:param name="GetPickSlipDetail_REQUEST" xml:id="id_289"/>
   <xsl:param name="globalClientID" xml:id="id_290"/>
   <xsl:param name="globalJobStatus" xml:id="id_292"/>
   <xsl:param name="globalLotItem" xml:id="id_293"/>
   <xsl:param name="globalLotItemArray" xml:id="id_294"/>
   <xsl:param name="globalLotQty" xml:id="id_295"/>
   <xsl:param name="globalPickLine" xml:id="id_296"/>
   <xsl:param name="globalPickLineArray" xml:id="id_297"/>
   <xsl:param name="globalRemainQty" xml:id="id_298"/>
   <xsl:param name="globalTransferedQty" xml:id="id_299"/>
   <xsl:param name="self" xml:id="id_300"/>
   <xsl:param name="tracking_var_1" xml:id="id_301"/>
   <xsl:param name="tracking_var_2" xml:id="id_302"/>
   <xsl:param name="tracking_var_3" xml:id="id_303"/>
   <xsl:template match="/" xml:id="id_11">
      <nstrgmpr:submitESSJobRequest xml:id="id_12">
         <nstrgmpr:jobPackageName xml:id="id_37">
            <xsl:value-of xml:id="id_38" select="$ESSJobPackageName"/>
         </nstrgmpr:jobPackageName>
         <nstrgmpr:jobDefinitionName xml:id="id_35">
            <xsl:value-of xml:id="id_36" select="$ESSJobDefinitionName"/>
         </nstrgmpr:jobDefinitionName>
         <nstrgmpr:paramList xml:id="id_41">
            <xsl:value-of xml:id="id_94" select="xsd:integer ($globalOrgID )"/>
         </nstrgmpr:paramList>
         <nstrgmpr:paramList xml:id="id_41">
            <xsl:value-of xml:id="id_96" select="$globalMRNumber"/>
         </nstrgmpr:paramList>
         <nstrgmpr:paramList xml:id="id_42">
            <xsl:value-of xml:id="id_45" select="$globalMRNumber"/>
         </nstrgmpr:paramList>
         <nstrgmpr:paramList xml:id="id_42">
            <xsl:value-of xml:id="id_71" select="&quot;&quot;"/>
         </nstrgmpr:paramList>
         <nstrgmpr:paramList xml:id="id_42">
            <xsl:value-of xml:id="id_127" select="&quot;&quot;"/>
         </nstrgmpr:paramList>
         <nstrgmpr:paramList xml:id="id_42">
            <xsl:value-of xml:id="id_128" select="&quot;&quot;"/>
         </nstrgmpr:paramList>
         <nstrgmpr:paramList xml:id="id_42">
            <xsl:value-of xml:id="id_129" select="&quot;&quot;"/>
         </nstrgmpr:paramList>
         <nstrgmpr:paramList xml:id="id_42">
            <xsl:value-of xml:id="id_130" select="&quot;&quot;"/>
         </nstrgmpr:paramList>
         <nstrgmpr:paramList xml:id="id_42">
            <xsl:value-of xml:id="id_134" select="&quot;&quot;"/>
         </nstrgmpr:paramList>
         <nstrgmpr:paramList xml:id="id_42">
            <xsl:value-of xml:id="id_132" select="&quot;&quot;"/>
         </nstrgmpr:paramList>
         <nstrgmpr:paramList xml:id="id_42">
            <xsl:value-of xml:id="id_135" select="&quot;&quot;"/>
         </nstrgmpr:paramList>
         <nstrgmpr:paramList xml:id="id_42">
            <xsl:value-of xml:id="id_136" select="&quot;&quot;"/>
         </nstrgmpr:paramList>
         <nstrgmpr:paramList xml:id="id_42">
            <xsl:value-of xml:id="id_137" select="&quot;2&quot;"/>
         </nstrgmpr:paramList>
         <nstrgmpr:paramList xml:id="id_42">
            <xsl:value-of xml:id="id_138" select="&quot;99&quot;"/>
         </nstrgmpr:paramList>
         <nstrgmpr:paramList xml:id="id_42">
            <xsl:value-of xml:id="id_139" select="&quot;&quot;"/>
         </nstrgmpr:paramList>
         <nstrgmpr:paramList xml:id="id_42">
            <xsl:value-of xml:id="id_140" select="&quot;&quot;"/>
         </nstrgmpr:paramList>
         <nstrgmpr:paramList xml:id="id_42">
            <xsl:value-of xml:id="id_141" select="&quot;&quot;"/>
         </nstrgmpr:paramList>
         <nstrgmpr:paramList xml:id="id_42">
            <xsl:value-of xml:id="id_142" select="&quot;&quot;"/>
         </nstrgmpr:paramList>
         <nstrgmpr:paramList xml:id="id_42">
            <xsl:value-of xml:id="id_143" select="&quot;Y&quot;"/>
         </nstrgmpr:paramList>
         <nstrgmpr:paramList xml:id="id_42">
            <xsl:value-of xml:id="id_146" select="&quot;&quot;"/>
         </nstrgmpr:paramList>
         <nstrgmpr:paramList xml:id="id_42">
            <xsl:value-of xml:id="id_144" select="&quot;&quot;"/>
         </nstrgmpr:paramList>
         <nstrgmpr:paramList xml:id="id_42">
            <xsl:value-of xml:id="id_145" select="&quot;&quot;"/>
         </nstrgmpr:paramList>
         </nstrgmpr:submitESSJobRequest>
   </xsl:template>
</xsl:stylesheet>